name: 'Run Tests'
description: 'Runs the preflight checks and integration tests.'

inputs:
    working-directory:
        description: 'The working directory to run the tests in.'
        required: false
        default: '.'

runs:
    using: 'composite'
    steps:
        - name: '📝 Print Inputs'
          shell: 'bash'
          env:
              JSON_INPUTS: '${{ toJSON(inputs) }}'
          run: 'echo "$JSON_INPUTS"'
        - name: 'Run Tests'
          working-directory: '${{ inputs.working-directory }}'
          run: |-
              echo "::group::Build"
              pnpm build
              echo "::group::Lint"
              pnpm lint
              echo "::group::Format::check"
              pnpm format:check
          shell: 'bash'
